---
title: "Lab Exercise 1"
author: "Charles Daniel Songaling"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)

amazon_watch1 <- data.frame()
scrapecat <- "watch"
url1 <- "https://www.amazon.sg/s?k=Watch&crid=KV3ASJWTVEUX&qid=1708563933&sprefix=watch%2Caps%2C393&ref=sr_pg_1"

session1 <- bow(url1, user_agent = "Educational")

watch1 <- scrape(session1) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch1_100 <- watch1[1:34]

watch1_price <- scrape(session1) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price1_100 <- watch1_price[1:34]

watch1_ratings <- scrape(session1) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings1_100 <- watch1_ratings[1:34]

watch1_reviews <- scrape(session1) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews1_100 <- watch1_reviews[1:34]


amazon_watch1 <- rbind(amazon_watch1, data.frame(category = "Watch",
                                                     Name = watch1_100,
                                                     Price = price1_100,
                                                     Ratings = ratings1_100,
                                                     Num_of_Reviews = reviews1_100))


url2 <- "https://www.amazon.sg/s?k=Watch&page=2&crid=KV3ASJWTVEUX&qid=1708563959&sprefix=watch%2Caps%2C393&ref=sr_pg_2"

session2 <- bow(url2, user_agent = "Educational")

watch2 <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch2_100 <- watch2[1:34]

watch2_price <- scrape(session2) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price2_100 <- watch2_price[1:34]

watch2_ratings <- scrape(session2) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings2_100 <- watch2_ratings[1:34]

watch2_reviews <- scrape(session2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews2_100 <- watch2_reviews[1:34]

amazon_watch2 <- data.frame()

amazon_watch2 <- rbind(amazon_watch2, data.frame(category = "Watch",
                                                     Name = watch2_100,
                                                     Price = price2_100,
                                                     Ratings = ratings2_100,
                                                     Num_of_Reviews = reviews2_100))



url3 <- "https://www.amazon.sg/s?k=Watch&page=3&crid=KV3ASJWTVEUX&qid=1708562893&sprefix=watch%2Caps%2C393&ref=sr_pg_3"

session3 <- bow(url3, user_agent = "Educational")

watch3 <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch3_100 <- watch3[1:34]

watch3_price <- scrape(session3) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price3_100 <- watch3_price[1:34]

watch3_ratings <- scrape(session3) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings3_100 <- watch3_ratings[1:34]

watch3_reviews <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews3_100 <- watch3_reviews[1:34]

amazon_watch3 <- data.frame()

amazon_watch3 <- rbind(amazon_watch3, data.frame(category = "Watch",
                                                     Name = watch3_100,
                                                     Price = price3_100,
                                                     Ratings = ratings3_100,
                                                     Num_of_Reviews = reviews3_100))

amazon_watch_combined <- bind_rows(amazon_watch1, amazon_watch2, amazon_watch3)

#View(amazon_watch_combined)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% hmtl_text()
}

product_info <- function(link) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
    product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
    
    productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
      
    prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
    
    RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
    
    productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
    
  amazonwatch <- data.frame(Category = category,
                            ProductName = Product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = prodRatings)
  
  return(amazonwatch)
}
```

```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watch"

scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
product_info <- function(link, category) {
  session <- bow(link, user_agent = "Educational")
  
  Sys.sleep(5)
  
  product <- scrapeNodes(session, "hi.a-size-large.a-text-ellipsis")
  
  productReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
  prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
  RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
  productRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatch <- data.frame(Category = category,
                            ProductName = product,
                            Reviewer = productReviewer,
                            Review = prodReview,
                            ReviewDate = RevDate,
                            Rating = productRatings)
  
  return(amazonwatch)
}

link <- "https://www.amazon.sg/Seiko-SND411P-Mens-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- product_info(link, category)

url2 <- "https://www.amazon.sg/Seiko-SND411P-Mens-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- product_info(link, category)

url3 <- "https://www.amazon.sg/Seiko-SND411P-Mens-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- product_info(link, category)

productreview <- rbind(pg1, pg2, pg3)
View(productreview)
```