---
title: "Lab Exercise 1"
author: "Charles Daniel Songaling"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)

amazon_watch1 <- data.frame()
scrapecat <- "watch"
url1 <- "https://www.amazon.sg/s?k=Watch&crid=KV3ASJWTVEUX&qid=1708563933&sprefix=watch%2Caps%2C393&ref=sr_pg_1"

session1 <- bow(url1, user_agent = "Educational")

watch1 <- scrape(session1) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch1_100 <- watch1[1:34]

watch1_price <- scrape(session1) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price1_100 <- watch1_price[1:34]

watch1_ratings <- scrape(session1) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings1_100 <- watch1_ratings[1:34]

watch1_reviews <- scrape(session1) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews1_100 <- watch1_reviews[1:34]


amazon_watch1 <- rbind(amazon_watch1, data.frame(category = "Watch",
                                                     Name = watch1_100,
                                                     Price = price1_100,
                                                     Ratings = ratings1_100,
                                                     Num_of_Reviews = reviews1_100))


url2 <- "https://www.amazon.sg/s?k=Watch&page=2&crid=KV3ASJWTVEUX&qid=1708563959&sprefix=watch%2Caps%2C393&ref=sr_pg_2"

session2 <- bow(url2, user_agent = "Educational")

watch2 <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch2_100 <- watch2[1:34]

watch2_price <- scrape(session2) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price2_100 <- watch2_price[1:34]

watch2_ratings <- scrape(session2) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings2_100 <- watch2_ratings[1:34]

watch2_reviews <- scrape(session2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews2_100 <- watch2_reviews[1:34]

amazon_watch2 <- data.frame()

amazon_watch2 <- rbind(amazon_watch2, data.frame(category = "Watch",
                                                     Name = watch2_100,
                                                     Price = price2_100,
                                                     Ratings = ratings2_100,
                                                     Num_of_Reviews = reviews2_100))



url3 <- "https://www.amazon.sg/s?k=Watch&page=3&crid=KV3ASJWTVEUX&qid=1708562893&sprefix=watch%2Caps%2C393&ref=sr_pg_3"

session3 <- bow(url3, user_agent = "Educational")

watch3 <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text

watch3_100 <- watch3[1:34]

watch3_price <- scrape(session3) %>%
  html_nodes("span.a-price-whole") %>%
  html_text

price3_100 <- watch3_price[1:34]

watch3_ratings <- scrape(session3) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text

ratings3_100 <- watch3_ratings[1:34]

watch3_reviews <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text

reviews3_100 <- watch3_reviews[1:34]

amazon_watch3 <- data.frame()

amazon_watch3 <- rbind(amazon_watch3, data.frame(category = "Watch",
                                                     Name = watch3_100,
                                                     Price = price3_100,
                                                     Ratings = ratings3_100,
                                                     Num_of_Reviews = reviews3_100))

amazon_watch_combined <- bind_rows(amazon_watch1, amazon_watch2, amazon_watch3)

#View(amazon_watch_combined)
```

```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Seiko-SND411P-Wristwatch-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Seiko-SND411P-Wristwatch-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Seiko-SND411P-Wristwatch-Silver-Color/product-reviews/B001KESEEO/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews <- rbind(pg1, pg2, pg3)

#View(Prodreviews)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Casio-MDV106-1AV-Analog-Watch-Black/product-reviews/B009KYJAJY/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Casio-MDV106-1AV-Analog-Watch-Black/product-reviews/B009KYJAJY/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Casio-MDV106-1AV-Analog-Watch-Black/product-reviews/B009KYJAJY/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews2 <- rbind(pg1, pg2, pg3)

#View(Prodreviews2)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Timex-Expedition-Scout-Watch-Classic/product-reviews/B07FFBHM7F/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Timex-Expedition-Scout-Watch-Classic/product-reviews/B07FFBHM7F/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Timex-Expedition-Scout-Watch-Classic/product-reviews/B07FFBHM7F/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews3 <- rbind(pg1, pg2, pg3)

#View(Prodreviews3)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Casio-MDV106-1AV-Black-MDV106-1A-Quartz/product-reviews/B09GKTMSS3/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Casio-MDV106-1AV-Black-MDV106-1A-Quartz/product-reviews/B09GKTMSS3/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Casio-MDV106-1AV-Black-MDV106-1A-Quartz/product-reviews/B09GKTMSS3/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews4 <- rbind(pg1, pg2, pg3)

#View(Prodreviews4)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Timex-Unisex-T2N647-Weekender-Chrome/product-reviews/B0070Y60K8/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Timex-Unisex-T2N647-Weekender-Chrome/product-reviews/B0070Y60K8/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Timex-Unisex-T2N647-Weekender-Chrome/product-reviews/B0070Y60K8/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews5 <- rbind(pg1, pg2, pg3)

#View(Prodreviews5)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Timex-Mens-Expedition-Scout-Watch/product-reviews/B09RTQGH4W/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Timex-Mens-Expedition-Scout-Watch/product-reviews/B09RTQGH4W/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Timex-Mens-Expedition-Scout-Watch/product-reviews/B09RTQGH4W/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews6 <- rbind(pg1, pg2, pg3)

#View(Prodreviews6)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Fossil-Townsman-Stainless-Leather-Chronograph/product-reviews/B01MQ5V6ZR/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Fossil-Townsman-Stainless-Leather-Chronograph/product-reviews/B01MQ5V6ZR/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Fossil-Townsman-Stainless-Leather-Chronograph/product-reviews/B01MQ5V6ZR/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews7 <- rbind(pg1, pg2, pg3)

#View(Prodreviews7)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Citizen-Eco-Drive-Promaster-Stainless-Polyurethane/product-reviews/B09CG2VP33/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Citizen-Eco-Drive-Promaster-Stainless-Polyurethane/product-reviews/B09CG2VP33/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Citizen-Eco-Drive-Promaster-Stainless-Polyurethane/product-reviews/B09CG2VP33/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews8 <- rbind(pg1, pg2, pg3)

#View(Prodreviews8)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/Orient-Sporty-Seventees-SOLAR-Wristwatch/product-reviews/B01BV43QHC/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/Orient-Sporty-Seventees-SOLAR-Wristwatch/product-reviews/B01BV43QHC/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/Orient-Sporty-Seventees-SOLAR-Wristwatch/product-reviews/B01BV43QHC/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews9 <- rbind(pg1, pg2, pg3)

#View(Prodreviews9)
```
```{r}
library(httr)
library(rvest)
library(selectr)

category <- "Watches"
scrapeNodes <- function(session, HTML) {
  session %>% scrape() %>% html_nodes(HTML) %>% html_text()
}
productinfo <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")
  Sys.sleep(5) 
        Product <- scrapeNodes(session, "h1.a-size-large.a-text-ellipsis")
  
        prodReviewer <- scrapeNodes(session, "span.a-profile-name")[1:10]
  
        prodReview <- scrapeNodes(session, "span.a-size-base.review-text.review-text-content")[1:10]
  
        RevDate <- scrapeNodes(session, "span.a-size-base.a-color-secondary.review-date")[1:10]
  
        prodRatings <- scrapeNodes(session, "span.a-icon-alt")[1:10]
  
  amazonwatches <- data.frame(Category = category,
                        ProductName = Product,
                        Reviewer = prodReviewer,
                        Review = prodReview,
                        ReviewDate = RevDate,
                        Rating = prodRatings)
  return(amazonwatches)
}

link1 <- "https://www.amazon.sg/SEIKO-Essentials-Watch-Women-Rectangular/product-reviews/B093565212/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
pg1 <- productinfo(link1)
link2 <- "https://www.amazon.sg/SEIKO-Essentials-Watch-Women-Rectangular/product-reviews/B093565212/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
pg2 <- productinfo(link2)
link3 <- "https://www.amazon.sg/SEIKO-Essentials-Watch-Women-Rectangular/product-reviews/B093565212/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
pg3 <- productinfo(link3)
Prodreviews10 <- rbind(pg1, pg2, pg3)

#View(Prodreviews10)
```